zotero:
  user_id: ${oc.env:ZOTERO_ID}
  api_key: ${oc.env:ZOTERO_KEY}
  include_path: ["transition-metal-compounds-Daniel I. Khomskii/**","triangular/**"]

email:
  sender: ${oc.env:SENDER}
  receiver: ${oc.env:RECEIVER}
  smtp_server: smtp.qq.com
  smtp_port: 465
  sender_password: ${oc.env:SENDER_PASSWORD}

llm:
  api:
    key: ${oc.env:OPENAI_API_KEY}
    base_url: ${oc.env:OPENAI_API_BASE}
  generation_kwargs:
    model: deepseek-chat

source:
  arxiv:
    category: ["cond-mat.str-el","cond-mat.mes-hall","cond-mat.supr-con"]

executor:
  debug: ${oc.env:DEBUG,null}
  source:
    - arxiv
  reranker: local 
