zotero:
  user_id: ${oc.env:ZOTERO_ID}
  api_key: ${oc.env:ZOTERO_KEY}
  include_path:
    - "the_heavy_fermion"
    - "the_heavy_fermion/**"

email:
  sender: ${oc.env:SENDER}
  receiver: ${oc.env:RECEIVER}
  smtp_server: smtp.qq.com
  smtp_port: 465
  sender_password: ${oc.env:SENDER_PASSWORD}

llm:
  api:
    key: ${oc.env:OPENAI_API_KEY}
    base_url: ${oc.env:OPENAI_API_BASE}

  generation_kwargs:
    model: deepseek-chat
    max_tokens: 8192

  language: Chinese

source:
  arxiv:
    category:
      - "cond-mat.str-el"
      - "cond-mat.mtrl-sci"
      - "cond-mat.mes-hall"
    include_cross_list: true

executor:
  debug: ${oc.env:DEBUG,null}
  send_empty: false
  max_paper_num: 20
  source:
    - "arxiv"
  reranker: local
